Parameters:
  ReadinessStartPlayer:
    PurposeInfo: Determines if the Player should be started
    AllowedValuesInfo:
    - startbefore
    - startafter
    - nostart
    Value: startafter
  ReadinessMode:
    PurposeInfo: Output of the Readiness tool
    AllowedValuesInfo:
    - silent
    - normal
    - verbose
    Value: normal
  ReadinessOutputFolder:
    PurposeInfo: Output of the Readiness tool
    AllowedValuesInfo:
    - Folder name
    - USERTEMPFOLDER
    - keep empty for the app folder
    Value: ''
CheckRanges:
  OperatingSystemCheck:
    PurposeInfo: Checks if the operating system generally is suitable
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: operating system name
    ValidValues:
    - name: OS
      value: Windows 8
    - name: OS
      value: Windows 10
  OperatingSystem64bitCheck:
    PurposeInfo: Checks if the operating system has 64bit architecture
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: Is64bit , true|false
    ValidValues:
    - name: Is64bit
      value: true
  OperatingSystemTypeCheck:
    PurposeInfo: Checks if the operating system is suitable
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: operating system property
    ValidValues:
    - name: 64bitexpected
      value: true
  UserRoleCheck:
    PurposeInfo: Checks if the user role is suitable
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: role
    ValidValues:
    - name: role
      value: Administrator
    - name: role
      value: User
  MemoryInstalledCheck:
    PurposeInfo: Checks if there is enough memory installed
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: GB
    ValidValues:
    - name: MinimalMemoryInstalled
      value: 2
  MemoryAvailableCheck:
    PurposeInfo: Checks if there is enough memory available
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: GB
    ValidValues:
    - name: MinimalMemoryAvailable
      value: 0,5
  TouchScreenCheck:
    PurposeInfo: Checks if the device has a touch screen
    RunThisCheck: true
    OptionalCheck: true
    UnitInfo: '-'
    ValidValues:
    - name: TouchScreenExpected
      value: true
  AntiVirusSoftwareCheck:
    PurposeInfo: Checks for anti virus software
    RunThisCheck: true
    OptionalCheck: true
    UnitInfo: '-'
    ValidValues:
    - name: AntiVirusSoftwareExpected
      value: true
  ScreenResolutionCheck:
    PurposeInfo: Checks if the horizontal screen resolution ist sufficient
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: Pixels
    ValidValues:
    - name: MinimalHorizontalRes
      value: 1024
    - name: MinimalVerticalRes
      value: 768
  NetworkConnectivityCheck:
    PurposeInfo: Checks if the internet is reachable
    RunThisCheck: true
    OptionalCheck: true
    UnitInfo: '-'
    ValidValues:
    - name: WebClientURL
      value: http://www.google.com/
    - name: WebClientURLaccessExpected
      value: true
    - name: PingURL
      value: www.google.com
    - name: PingURLaccessExpected
      value: true
  RegistryKeyCheck:
    PurposeInfo: Registry check. Apply keys, vars and expected values or 'not set'
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: '-'
    ValidValues:
    - name: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\;DisableLockWorkstation
      value: not set
  PortRangeAvailableCheck:
    PurposeInfo: Checks if the ports needed by the player are available. Specify a range of ports
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: port number
    ValidValues:
    - name: FirstPort
      value: 8000
    - name: LastPort
      value: 8999
    - name: MinimumPortsFree
      value: 10
  PortAvailableCheck:
    PurposeInfo: Checks if the ports needed by the player are available. Specify a list of ports
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: port number
    ValidValues:
    - name: Port
      value: 8000
    - name: Port
      value: 8001
  FoldersWritableCheck:
    PurposeInfo: Checks if a folder is writable.
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: Folder, <FolderName> or one of [USERTEMPFOLDER, ROOTDRIVE]
    ValidValues:
    - name: Folder
      value: USERTEMPFOLDER
    - name: Folder
      value: ROOTDRIVE
  FoldersFreeSpaceCheck:
    PurposeInfo: Checks if a folder has sufficient free space
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: <FolderName> or one of [USERTEMPFOLDER, ROOTDRIVE], expected free space in MB
    ValidValues:
    - name: C:\Users\<USER>\AppData\Local\Temp\
      value: 500
    - name: C:\
      value: 1024
  DriveSpeedCheck:
    PurposeInfo: Checks the data transfer speed
    RunThisCheck: true
    OptionalCheck: true
    UnitInfo: MB/s
    ValidValues:
    - name: MinimalSpeedRead
      value: 20
    - name: MinimalSpeedWrite
      value: 7
  AudioMidiToneCheck:
    PurposeInfo: Checks if a midi tone can be played
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: '-'
    ValidValues: []
  AudioDevicesCheck:
    PurposeInfo: Checks if there are audio devices
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: '-'
    ValidValues: []
  ExternalSoftwareCheck:
    PurposeInfo: Checks for external programs to exist
    RunThisCheck: true
    OptionalCheck: false
    UnitInfo: Folder , Program file name
    ValidValues:
    - name: ''
      value: TestApp.Player.Chromely.exe
