name: Build IRTlibReadiness Tool 
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Prepare Release Folder      
      run: mkdir ${{ github.workspace }}/ReadinessTool
    - name: Publish
      run: dotnet publish -o "${{ github.workspace }}\ReadinessTool\"
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}\ReadinessTool\      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReadinessTool.exe
        path:  ${{ github.workspace }}\ReadinessTool\*.exe  
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "IRTlibReadiness Console Application"
          files: |
             ReadinessTool/ReadinessTool.exe
